import { MainLayout } from '@/components/layout'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { NextPageWithLayout } from '../models'
import styles from '../styles/Home.module.css'

const Home: NextPageWithLayout = () => {
  const router = useRouter();

  const handleGoToDetailPage = () => {
    router.push('/posts/1')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Manhprovip123</a>
        </h1>

        <Link href="/about">
          <a>About us</a> 
        </Link>

        <button onClick={handleGoToDetailPage}>Go to post detail</button>
      </main>
    </div>
  )
}

Home.Layout = MainLayout

export default Home
